services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Exposes frontend on port 5173
    networks:
      - hospital-net
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" # Exposes backend on port 8000
    networks:
      - hospital-net
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development

    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  hospital-net:
    driver: bridge
